repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.0
    hooks:
      # - id: dbt-deps
      - id: dbt-parse
        args:
          [
            "--cmd-flags",
            "++profiles-dir",
            ".",
            "++project-dir",
            ".",
            "++no-partial-parse",
          ]
      - id: check-model-columns-have-desc
