repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.1
    hooks:
      - id: dbt-deps
        args: ["--cmd-flags", "++debug"]
      # - id: dbt-parse
      #   args:
      #     [
      #       "--cmd-flags",
      #       "++profiles-dir",
      #       ".",
      #       "++project-dir",
      #       ".",
      #       "++no-partial-parse",
      #     ]
      # - id: check-model-columns-have-desc
