name: Quality Checks

on:
  # - pull_request
  - push

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT_ID: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
      SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_USER_ROLE: ${{ secrets.SNOWFLAKE_USER_ROLE }}
      SNOWFLAKE_DATABASE_NAME: ${{ secrets.SNOWFLAKE_DATABASE_NAME }}
      SNOWFLAKE_WAREHOUSE_NAME: ${{ secrets.SNOWFLAKE_WAREHOUSE_NAME }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      # - name: Paths Changes Filter
      #   id: get_file_changes
      #   uses: dorny/paths-filter@v3.0.2
      #   with:
      #     list-files: escape
      #     filters: |
      #       models:
      #         - added|modified: 'models/**/*.{sql,yml}'

      # - name: Generate File Pairs
      #   id: file_pairs
      #   uses: ./.github/actions/generate-file-pairs
      #   with:
      #     changed-files: ${{ steps.get_file_changes.outputs.models_files }}

      - name: Install dbt-checkpoint
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake pre-commit

      - name: Run dbt-checkpoint
        run: |
          pre-commit run --all-files
          # pre-commit run --files ${{ steps.get_file_changes.outputs.models_files}}
