name: Quality Checks

on:
  # - pull_request
  - push

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Paths Changes Filter
        id: get_file_changes
        uses: dorny/paths-filter@v3.0.2
        with:
          list-files: escape
          filters: |
            models_and_props:
              - added|modified: '**/*.{sql,yml,yaml}'

      - name: Run dbt Checkpoint
        if: ${{ steps.get_file_changes.outputs.models_and_props == 'true' }}
        uses: dbt-checkpoint/action@v0.1
        with:
          extra_args: >
            --files ${{ steps.get_file_changes.outputs.models_and_props_files}}
          dbt_version: 1.7.3
          dbt_adapter: dbt-snowflake
