name: Quality Checks

on:
  # - pull_request
  - push

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        env:
          YQ_VERSION: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake pre-commit
          sudo wget $YQ_VERSION -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          dbt parse

      - name: Paths Changes Filter
        id: get_file_changes
        uses: dorny/paths-filter@v3.0.2
        with:
          list-files: escape
          filters: |
            models:
              - added|modified: 'models/**/_*.yml'

      - name: Properties Validations
        # if: ${{ steps.get_file_changes.outputs.models == 'true' }}
        run: |
          set -eux
          # Check mandatory fields (name, desccription, and columns)
          yq eval \
            '["name", "description", "columns"] - (.models.[0] | keys) | length == 0' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check name is not empty
          yq eval \
            '.models.[0].name | length > 0' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check description is not empty
          yq eval \
            '.models.[0].description | length > 0' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check if columns has name
          yq eval \
            '[.models.[0].columns[] | has("name")] | all' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check if columns has description
          yq eval \
            '[.models.[0].columns[] | has("description")] | all' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check if column name is not empty
          yq eval \
            '.models.[0].columns | all_c(.name | length > 0)' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
          # Check if column description is not empty
          yq eval \
            '.models.[0].columns | all_c(.description | length > 0)' \
            ${{ steps.get_file_changes.outputs.models_files }} -e
